apiVersion: v1
kind: Service
metadata:
  name: {{ template "demo2.fullname" . }}-api
  labels:
    app: {{ template "demo2.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.externalPort }}
      targetPort: {{ .Values.api.service.internalPort }}
      protocol: TCP
      name: {{ .Values.api.service.portName }}
{{- if (and (eq .Values.api.service.type "NodePort") (not (empty .Values.api.service.nodePort))) }}
      nodePort: {{ .Values.api.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "demo2.name" . }}
    release: {{ .Release.Name }}
